Nouvelles commandes
alljorn/bot-science-discord pull request #8
Opened 2023-05-16 19:33 UTC by AesirIvy

- Création du groupe article, `/article` -> `/article recent` & `/write` -> `/article write`.
- Nouvelle commande `/article search` pour retrouver les anciennes articles écrites par un utilisateur.
- Nouvelle commande `/article read` pour lire ces anciennes articles.
- `/show config` est devenu moins verbose, ne montre plus l'id du rôle.
- Les articles sont maintenant guild dépendant.
- Deux auteurs différents ne peuvent plus écrire un article ayant le même titre.

2023-05-16 21:41 UTC, alljorn requested changes
La fonction initialize_guild a été supprimer or elle est nécessaire à l'ajout des serveurs à la base de  données

2023-05-16 21:48 UTC, alljorn reviewed
tu pourrais me parler de tes idées aussi avant vu que c'est mon projet à la base j'aimerai être au courant de tes bonnes idées TwT

2023-05-17 17:29 UTC, alljorn reviewed
pourquoi avoir ajouter une commande register_guild alors la méthode précédente le permettait de magnière automatique ?

2023-05-17 17:30 UTC, alljorn requested changes
incohérence au niveau de la commande /show_config, le texte est afficher en gras et en italique, ne devrait-il pas être soit l'un soit l'autre ?

2023-05-17 17:32 UTC, alljorn requested changes
si tu veux implémenter la commande /register_guild alors il faut gérer les autres commandes pour qu'elles ne provoquent pas d'erreur quand le serveur n'est pas enregistré dans la base de donnée

2023-05-17 17:37 UTC, alljorn approved these changes
les nouvelles commandes 'article' sont très bien pensées et fonctionnes bien

2023-05-17 17:41 UTC, alljorn reviewed
Je me demmandais si il n'était pas mieux que pour les articles qu'il soit unique par utilisateur et non par guild, de telle sorte plusieurs personne peuvent traiter du même sujet et ainsi la commande /article read pourra proposer  différend titre si il existe plusieurs auteur

2023-05-17 17:42 UTC, alljorn requested changes
bug sur la commande /article read
j'ai créer un article "Test" et en fournissant le titre en minuscule "test" le bot rencontre une erreur

2023-05-17 18:49 UTC, AesirIvy commented
> pourquoi avoir ajouter une commande register_guild alors la méthode précédente le permettait de magnière automatique ?

`register_guild` a été ajouté car rien ne garantie que `/article` soit utilisé avant `/write` ou autres commandes.
La méthode la plus commode, c'est de proposer `register_guild` à l'event `on_guild_join`, mais cela requiert l'intent manage guild, donc je te laisse juger.

> si tu veux implémenter la commande /register_guild alors il faut gérer les autres commandes pour qu'elles ne provoquent pas d'erreur quand le serveur n'est pas enregistré dans la base de donnée

Si le guild` n'est pas dans la database, `/register_guild` doit être justement utilisé.

> incohérence au niveau de la commande /show_config, le texte est afficher en gras et en italique, ne devrait-il pas être soit l'un soit l'autre ?

Bien vu, le gras a été conservé.

> bug sur la commande /article read j'ai créer un article "Test" et en fournissant le titre en minuscule "titre" le bot rencontre une erreur

Ça, c'est parce que j'ai oublié de gérer lorsque la commande ne trouve pas d'articles. Plus tard, il faudra une commande similarité pour pouvoir proposer des articles semblabes.

> Je me demmandais si il n'était pas mieux que pour les articles qu'il soit unique par utilisateur et non par guild, de telle sorte plusieurs personne peuvent traiter du même sujet et ainsi la commande /article read pourra proposer différend titre si il existe plusieurs auteur

C'est le job du directeur de rédaction de décider de l'article à conserver.
Puis je manque d'enthousiasme pour le mettre en œuvre (autre façon de dire : j'ai la flemme).

2023-05-17 19:10 UTC, alljorn commented
pourquoi les commandes /article ne peuvent pas implémenter le même systeme d'initialisation que les autres commandes ?
et d'accord si on garde la command /register_guild alors il faut au moins que le bot envoie un message d'erreur à l'utilisateur si le serveur n'est pas présent dans la db
Je comprend que t'es la flemme et oui c'est au directeur de gerer 👍

2023-05-17 22:39 UTC, AesirIvy commented
On ferra en sorte que le bot ajoute tous les guilds manquant au démarrage, et lors de l'event `on_guild_join`. Le `WelcomeEmbed()` pourra très bien servir dans `/help`. Pourquoi on demande aux utilisateurs de cliquer sur initialiser, ce n'est pas comme si on leur proposait des cookies ?
Car là, j'ai horreur quel cette fonction s'invite dans toutes les commandes.

2023-05-18 09:14 UTC, alljorn approved these changes
le retour de la fonction initialize_guild est bien implémenté

2023-05-18 09:16 UTC, alljorn commented
> On ferra en sorte que le bot ajoute tous les guilds manquant au démarrage, et lors de l'event `on_guild_join`. Le `WelcomeEmbed()` pourra très bien servir dans `/help`. Pourquoi on demande aux utilisateurs de cliquer sur initialiser, ce n'est pas comme si on leur proposait des cookies ? Car là, j'ai horreur que cette fonction s'invite dans toutes les commandes.

Je vais merge je te laisse carte blanche pour le prochaine pull

2023-05-18 09:18 UTC, merged