finishing article related commands
alljorn/bot-science-discord pull request #9
Opened 2023-05-18 13:34 UTC by AesirIvy

- Ajout automatique du guild dans la base de données
- Création de la commande `/article delete`

N'oublie pas d'ajouter
```
intents = discord.Intents.default()
intents.guilds = True
```
dans `config.py`

2023-05-18 19:22 UTC, alljorn requested changes
L'ajout automatique des serveurs dans la base de données est une excellente initiative cependant si la base de données est réinitialisé pour une quelconque raison, les serveurs qui ont Science bot devrait alors expulser puis réinviter le bot ce qui n'est pas du tout pratique
Peut être est il envisageable de faire quelque chose dans le on_ready ? je ne me suis pas renseigner j'espère que tu vois une solution
Encore merci de ton investisment ! personnellement je n'ai pas trop le temps de travailler le bot la journée mais seulement le soir donc c'est vraiment très agréable de voir le bot avancer si vite grâce à toi

2023-05-18 19:24 UTC, alljorn reviewed
je propose un commande /credit avec ton nom et le mien en tant que developpeur du bot et celui de science pour son idée original
je peux m'occuper de cette commande ne t'inquite pas TwT

2023-05-18 20:53 UTC, AesirIvy commented
> L'ajout automatique des serveurs dans la base de données est une excellente initiative cependant si la base de données est réinitialisé pour une quelconque raison, les serveurs qui ont Science bot devrait alors expulser puis réinviter le bot ce qui n'est pas du tout pratique, par exemple sur mon serveur c'est ce que je dois faire Peut être est il envisageable de faire quelque chose dans le on_ready ?

C'est vérifié dans main.py, lors du exécution. Regarde dans la section `if __name__ == "__main__":`.

> je propose un commande /credit avec ton nom et le mien en tant que developpeur du bot et celui de science pour son idée original je peux m'occuper de cette commande ne t'inquite pas TwT

Je ne suis pas fan d'avoir une liste de commandes trop longs, je propose d'ajouter le crédit dans `WelcomeConfigEmbed`. Il faudra d'ailleurs le renommer en `WelcomeEmbed`, puisqu'il n'y a plus de config.
Si tu as l'intention de garder le code open source, tu peux tout simplement link le repo dans la description du bot, comme cela, ils verront les contributeurs.

2023-05-19 22:54 UTC, alljorn requested changes
lorsqu'on supprime un article il est encore affiché par les commande /article recent et /article search
L'execution de la commande /article read avec le nom de l'article en question provoque une erreur
> FileNotFoundError: [Errno 2] No such file or directory: 'articles/1044006482842239086/Test'

2023-05-21 18:51 UTC, alljorn requested changes
je ne sait pas pourquoi parce que il n'y a aucun message d'erreur dans la console mais j'ai du executer deux fois la commande /article delete pour supprimer un article parce qu'à la première execution malgré la confiramation de la suppression l'article existait encore et à la deuxième tentative il a bien été supprimé
Ensuite j'ai supprimé un autre article mais il  est encore affiché dans /article recent et /article search mais n'existe plus dans le dossiers articles/

2023-05-21 22:09 UTC, AesirIvy commented
Je n'ai pas ce bug.

Vérifie que tu as bien le dernier patch avec `manager.DATABASE.commit()` dans `/article delete` à la ligne 40.
Puis qu'on ai le même config.py :
```python
# inside config.py

import discord
from discord.ext import commands


class Bot(commands.Bot):

    def __init__(self):
        intents = discord.Intents()
        intents.guilds = True
        super().__init__(intents=intents)


bot = Bot()
token =  # your token
```

2023-05-22 22:48 UTC, closed without merging